# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'GPlaceAPIExample' do
pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD'
end

target 'GPlaceAPIExampleTests' do

end

